# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VerificarSobreposicao
                                 A QGIS plugin
 Verifica sobreposição de feição
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-05
        copyright            : (C) 2024 by Annacezio de Brito
        email                : cesardb54@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VerificarSobreposicao class from file VerificarSobreposicao.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Verificar_Sobreposicao import VerificarSobreposicao
    return VerificarSobreposicao(iface)
